name: azeoo_profile_sdk
description: "An AZEOO Flutter SDK for displaying user profiles across multiple platforms (React Native, Android, iOS)"
version: 1.0.0
repository: https://github.com/puvistyne-tech/azeoo_profile_sdk

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  retrofit: ^4.1.0
  flutter_riverpod: ^2.4.9
  envied: ^1.1.1
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.stein.fluttermodule
    iosBundleIdentifier: com.stein.fluttermodule
